# Generated by Django 3.0.6 on 2022-07-12 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
    ]
