# Generated by Django 3.0.6 on 2022-07-12 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bestsellerstatus',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
