# Generated by Django 3.0.6 on 2022-07-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20220715_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discountstatus',
            field=models.BooleanField(default=False),
        ),
    ]
