# Generated by Django 3.0.6 on 2022-07-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_product_discountstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bestsellerstatus',
            field=models.BooleanField(default=False),
        ),
    ]
