# Generated by Django 3.0.6 on 2022-07-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20220715_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discountstatus',
            new_name='discount10',
        ),
        migrations.AddField(
            model_name='product',
            name='discount30',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='discount50',
            field=models.BooleanField(default=False),
        ),
    ]
